"""Modifica nome campo in POST

Revision ID: 18b67e1a5e72
Revises: 80b1e6905d22
Create Date: 2022-11-14 14:30:14.778634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b67e1a5e72'
down_revision = '80b1e6905d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.drop_column('descritpion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descritpion', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
